### ISSUE TITLE
Request to update http within package

### ISSUE THREAD

**Issue by codingiswhyicry** [bienvenuelisis/google_maps_directions#2]
Hi, first and foremost wanted to say thank you for putting this together. I'm trying to implement this in a web app that also uses Google Fonts, and I get this versioning error when trying to install the package. 

`Because google_fonts >=4.0.5 depends on http ^1.0.0 and every version of google_maps_directions depends on http ^0.13.5, google_fonts >=4.0.5 is incompatible with google_maps_directions. So, because [my_project] depends on both google_fonts ^5.1.0 and google_maps_directions any, version solving failed.`

Is there a reason why the package uses that particular version of HTTP, or can someone run flutter pub upgrade on the package so I can use it? Thanks :-)

**Comment by bienvenuelisis** [comment]
Hello, thank you for the interest to the package.

Release v.0.0.4 published with http version 1.1.0.

Feel free to reopen this issue if you encountered another error relative to this one.

**Comment by codingiswhyicry** [comment]
Thank you so much, much appreciated :-)
